
java.lang.NullPointerException
	at com.JSONtoExcelApplication.odm_Pre_prescriberPharmacistIPLst.process(odm_Pre_prescriberPharmacistIPLst.java:100)
	at com.JSONtoExcelApplication.ExcelGenerator.processJsonObject(ExcelGenerator.java:100)
	at com.JSONtoExcelApplication.ExcelGenerator.generateExcelFile(ExcelGenerator.java:63)
	at com.JSONtoExcelApplication.aMainRun.processJsonRequest(aMainRun.java:236)
	at com.JSONtoExcelApplication.aMainRun.runConversionWithOutputDirectory(aMainRun.java:155)
	at com.JSONtoExcelApplication.aMainRun.runConversion(aMainRun.java:75)
	at com.JSONtoExcelApplication.UserInputUI$4.lambda$0(UserInputUI.java:443)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.NullPointerException
	at com.JSONtoExcelApplication.odm_Pre_prescriberPharmacistIPLst.process(odm_Pre_prescriberPharmacistIPLst.java:100)
	at com.JSONtoExcelApplication.ExcelGenerator.processJsonObject(ExcelGenerator.java:100)
	at com.JSONtoExcelApplication.ExcelGenerator.generateExcelFile(ExcelGenerator.java:63)
	at com.JSONtoExcelApplication.aMainRun.processJsonRequest(aMainRun.java:236)
	at com.JSONtoExcelApplication.aMainRun.runConversionWithOutputDirectory(aMainRun.java:155)
	at com.JSONtoExcelApplication.aMainRun.runConversion(aMainRun.java:75)
	at com.JSONtoExcelApplication.UserInputUI$4.lambda$0(UserInputUI.java:443)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
