
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:507)
	at org.json.JSONObject.<init>(JSONObject.java:225)
	at org.json.JSONObject.<init>(JSONObject.java:414)
	at com.JSONtoExcelApplication.aMainRun.processJsonRequest(aMainRun.java:220)
	at com.JSONtoExcelApplication.aMainRun.runConversionWithOutputDirectory(aMainRun.java:162)
	at com.JSONtoExcelApplication.aMainRun.runConversion(aMainRun.java:75)
	at com.JSONtoExcelApplication.UserInputUI$4.lambda$0(UserInputUI.java:443)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:507)
	at org.json.JSONObject.<init>(JSONObject.java:225)
	at org.json.JSONObject.<init>(JSONObject.java:414)
	at com.JSONtoExcelApplication.aMainRun.processJsonRequest(aMainRun.java:220)
	at com.JSONtoExcelApplication.aMainRun.runConversionWithOutputDirectory(aMainRun.java:162)
	at com.JSONtoExcelApplication.aMainRun.runConversion(aMainRun.java:75)
	at com.JSONtoExcelApplication.UserInputUI$4.lambda$0(UserInputUI.java:443)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:507)
	at org.json.JSONObject.<init>(JSONObject.java:225)
	at org.json.JSONObject.<init>(JSONObject.java:414)
	at com.JSONtoExcelApplication.aMainRun.processJsonRequest(aMainRun.java:220)
	at com.JSONtoExcelApplication.aMainRun.runConversionWithOutputDirectory(aMainRun.java:162)
	at com.JSONtoExcelApplication.aMainRun.runConversion(aMainRun.java:75)
	at com.JSONtoExcelApplication.UserInputUI$4.lambda$0(UserInputUI.java:443)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
